# Generated by Django 4.2.6 on 2023-10-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post/', verbose_name='Image')),
                ('posted_time', models.DateTimeField(auto_now_add=True, verbose_name='Post_posted_time')),
                ('caption', models.CharField(blank=True, max_length=50, verbose_name='Caption')),
            ],
        ),
    ]
