# Generated by Django 4.2.6 on 2023-11-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post/post.png', upload_to='post_images/', verbose_name='Image'),
        ),
    ]
