# Generated by Django 4.2.6 on 2023-10-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reg_token',
        ),
    ]
