# Generated by Django 4.2.6 on 2023-10-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uchenik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uspeh', models.CharField(max_length=100)),
                ('creativnost', models.CharField(max_length=100)),
                ('potencial', models.CharField(max_length=100)),
            ],
        ),
    ]
