# Generated by Django 4.2.6 on 2023-10-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_test_delete_uchenik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='size',
            field=models.IntegerField(),
        ),
    ]
