# Generated by Django 4.2.6 on 2023-10-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_test_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='size',
        ),
    ]
